version: 2.1
jobs:
  build:
    tags:
      only: /^v.*/
    docker:
      - image: circleci/node:14.17.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "----- `node -v` -----"
      - run: echo "----- `npm -v` -----"
      - run: echo "----- install dependencies -----"
      - run: npm install
      - run: echo "----- build -----"
      - run: npm run build
      - run: echo "----- deploy -----"
      - add_ssh_keys:
          fingerprints:
            - "d0:7c:94:a3:6e:75:57:95:be:52:e1:20:0f:9b:72:18"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: echo "$REMOTE_HOSTKEY-$SSH_USER-$SSH_IP"
      - run: scp -r public $SSH_USER@$SSH_IP:~/code
      - run: echo "----- deploy done -----"
